import type { Metadata } from 'next';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { getActiveCategories, getActiveProducts } from '@/lib/catalog';
import { ShopCatalog } from '@/components/products/ShopCatalog';

const banners: Record<string, string> = { 'human-hair': 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1400&q=85', wigs: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=1400&q=85', bundles: 'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=1400&q=85', closures: 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=1400&q=85', frontals: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?auto=format&fit=crop&w=1400&q=85' };

type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const categories=await getActiveCategories();const category=categories.find(item=>item.slug===slug);return category?{title:category.name,description:category.description??`Shop ${category.name} from Cee2Sweet.`}:{title:'Collection not found'};}
export default async function Category({params}:Props){const {slug}=await params;const [categories,products]=await Promise.all([getActiveCategories(),getActiveProducts()]);const category=categories.find(item=>item.slug===slug);if(!category)notFound();const categoryProducts=products.filter(product=>product.category.slug===slug);const banner=banners[slug]??'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?auto=format&fit=crop&w=1400&q=85';return <div><section className="relative isolate overflow-hidden bg-ink text-white"><div className="absolute inset-0 -z-10 opacity-50"><Image src={banner} alt="" fill sizes="100vw" className="object-cover" /></div><div className="shell py-20"><p className="eyebrow text-white">Collection</p><h1 className="mt-2 font-display text-5xl md:text-6xl">{category.name}</h1><p className="mt-4 max-w-lg text-white/80">{category.description??`Explore our current ${category.name.toLowerCase()} selection.`}</p><p className="mt-6 text-sm text-white/80">{categoryProducts.length} {categoryProducts.length===1?'product':'products'}</p></div></section><div className="shell section"><ShopCatalog products={categoryProducts}/></div></div>}
