import { NextResponse } from 'next/server';
import { z } from 'zod';
import { createClient, hasSupabaseEnv } from '@/lib/supabase/server';
import { createClient as createAdminClient } from '@supabase/supabase-js';

const variantSchema=z.object({length:z.string().trim().max(30).optional(),color:z.string().trim().max(60).optional(),price:z.number().nonnegative(),compareAtPrice:z.number().nonnegative().optional(),stockQuantity:z.number().int().nonnegative(),sku:z.string().trim().min(1).max(80),options:z.record(z.string()).default({})});
const productSchema=z.object({name:z.string().trim().min(2).max(160),slug:z.string().trim().min(2).max(160).regex(/^[a-z0-9-]+$/),description:z.string().trim().max(5000).default(''),categoryId:z.string().uuid(),price:z.number().nonnegative(),compareAtPrice:z.number().nonnegative().optional(),brand:z.string().trim().max(100).optional(),hairType:z.string().trim().max(100).optional(),length:z.string().trim().max(30).optional(),color:z.string().trim().max(60).optional(),stockQuantity:z.number().int().nonnegative(),sku:z.string().trim().min(1).max(80),featured:z.boolean().default(false),variants:z.array(variantSchema).default([])});
async function admin(){if(!hasSupabaseEnv()||!process.env.SUPABASE_SERVICE_ROLE_KEY)return null;const session=await createClient();const {data:{user}}=await session.auth.getUser();if(!user)return null;const {data:profile}=await session.from('profiles').select('role').eq('id',user.id).single();if(profile?.role!=='admin')return null;return createAdminClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}})}
export async function POST(request:Request){const client=await admin();if(!client)return NextResponse.json({error:'Administrator access is required.'},{status:403});const parsed=productSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:'Please check the product fields.'},{status:400});const {variants,...product}=parsed.data;const {data:created,error}=await client.from('products').insert({name:product.name,slug:product.slug,description:product.description,category_id:product.categoryId,price:product.price,compare_at_price:product.compareAtPrice??null,brand:product.brand??null,hair_type:product.hairType??null,length:product.length??null,color:product.color??null,stock_quantity:product.stockQuantity,sku:product.sku,featured:product.featured}).select('id').single();if(error||!created)return NextResponse.json({error:'Unable to create product.'},{status:400});if(variants.length){const {error:variantError}=await client.from('product_variants').insert(variants.map(variant=>({product_id:created.id,length:variant.length??null,color:variant.color??null,price:variant.price,compare_at_price:variant.compareAtPrice??null,stock_quantity:variant.stockQuantity,sku:variant.sku,options:variant.options})));if(variantError)return NextResponse.json({error:'Product created, but variants could not be saved.'},{status:400})}return NextResponse.json({id:created.id},{status:201})}
