import { Product, Category } from '@/types/product';
export const categories:Category[]=[['human-hair','Human Hair'],['wigs','Wigs'],['bundles','Bundles'],['closures','Closures'],['frontals','Frontals'],['hair-extensions','Hair Extensions'],['braids','Braids'],['hair-accessories','Hair Accessories']].map(([slug,name])=>({id:slug,slug,name}));
export const products:Product[]=[
 {id:'1',name:'Honey Blonde Body Wave Wig',slug:'honey-blonde-body-wave-wig',description:'A soft honey blonde wig with a loose body-wave finish for an effortless statement look.',price:1450,compareAtPrice:1650,category:categories[1],brand:'Cee2Sweet Collection',hairType:'Human Hair',length:'22 inches',color:'Honey Blonde',stockQuantity:5,sku:'C2S-HBW22',featured:true,images:[{url:'/images/products/blonde-wave-wig.jpg',alt:'Honey blonde body wave wig'}]},
 {id:'2',name:'Natural Black Sleek Straight Wig',slug:'natural-black-sleek-straight-wig',description:'A smooth, natural black straight wig with a sleek finish and soft movement.',price:1250,category:categories[1],brand:'Cee2Sweet Collection',hairType:'Human Hair',length:'20 inches',color:'Natural Black',stockQuantity:8,sku:'C2S-NSS20',featured:true,isNew:true,images:[{url:'/images/products/black-sleek-straight-wig.jpg',alt:'Natural black sleek straight wig'}]},
 {id:'3',name:'Midnight Long Straight Wig',slug:'midnight-long-straight-wig',description:'A dramatic long straight style in a rich midnight black tone.',price:1500,category:categories[1],hairType:'Human Hair',length:'26 inches',color:'Midnight Black',stockQuantity:6,sku:'C2S-MLS26',featured:true,images:[{url:'/images/products/black-long-straight-wig.jpg',alt:'Midnight long straight wig'}]},
 {id:'4',name:'Blonde Ombre Wave Wig',slug:'blonde-ombre-wave-wig',description:'A dimensional blonde ombré wig with a relaxed wave and dark root blend.',price:1550,category:categories[1],hairType:'Human Hair',length:'24 inches',color:'Blonde Ombre',stockQuantity:4,sku:'C2S-BOW24',isNew:true,images:[{url:'/images/products/blonde-ombre-wave-wig.jpg',alt:'Blonde ombre wave wig'}]},
 {id:'5',name:'Platinum Silk Straight Wig',slug:'platinum-silk-straight-wig',description:'An extra-long platinum straight wig with a silky, high-impact finish.',price:1650,category:categories[1],hairType:'Human Hair',length:'28 inches',color:'Platinum Blonde',stockQuantity:3,sku:'C2S-PSS28',featured:true,images:[{url:'/images/products/platinum-straight-wig.jpg',alt:'Platinum silk straight wig'}]},
 {id:'6',name:'Icy Blonde Soft Wave Wig',slug:'icy-blonde-soft-wave-wig',description:'A long icy blonde wig with a soft, flowing wave texture.',price:1550,category:categories[1],hairType:'Human Hair',length:'26 inches',color:'Icy Blonde',stockQuantity:4,sku:'C2S-IBW26',featured:true,images:[{url:'/images/products/platinum-wave-wig.jpg',alt:'Icy blonde soft wave wig'}]},
 {id:'8',name:'Burgundy Afro Curl Wig',slug:'burgundy-afro-curl-wig',description:'A full-bodied burgundy afro curl wig made for standout texture and volume.',price:1200,category:categories[1],hairType:'Synthetic Fibre',length:'16 inches',color:'Burgundy',stockQuantity:6,sku:'C2S-BAC16',featured:true,isNew:true,images:[{url:'/images/products/burgundy-afro-curl-wig.jpg',alt:'Burgundy afro curl wig'}]},
];
products[0].variants=[{id:'demo-hbw-natural-18',productId:'1',length:'18 inches',color:'Natural Black',price:1350,stockQuantity:3,sku:'C2S-HBW18-NB',isActive:true},{id:'demo-hbw-natural-22',productId:'1',length:'22 inches',color:'Natural Black',price:1450,stockQuantity:5,sku:'C2S-HBW22-NB',isActive:true},{id:'demo-hbw-burgundy-22',productId:'1',length:'22 inches',color:'Burgundy',price:1500,stockQuantity:2,sku:'C2S-HBW22-BU',isActive:true}];
export const formatSLE=(n:number)=>`SLE ${new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n)}`;
export function getProduct(slug:string){return products.find(p=>p.slug===slug)}
