create extension if not exists "pgcrypto";
create type public.order_status as enum ('pending','confirmed','processing','ready_for_delivery','delivered','cancelled');
create type public.payment_status as enum ('pending','paid','failed','refunded');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, phone text, role text not null default 'customer' check (role in ('customer','admin')), created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, description text, created_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text not null default '', price numeric(12,2) not null check(price >= 0), compare_at_price numeric(12,2) check(compare_at_price >= 0), category_id uuid references public.categories(id) on delete set null, brand text, hair_type text, length text, color text, stock_quantity integer not null default 0 check(stock_quantity >= 0), sku text not null unique, featured boolean not null default false, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.product_images (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, image_url text not null, alt_text text, display_order integer not null default 0, created_at timestamptz not null default now());
create table public.orders (id uuid primary key default gen_random_uuid(), customer_id uuid references public.profiles(id) on delete set null, customer_name text not null, phone text not null, email text, district text not null, city text not null, delivery_address text not null, delivery_notes text, subtotal numeric(12,2) not null, delivery_fee numeric(12,2) not null default 0, total numeric(12,2) not null, payment_method text not null, payment_status public.payment_status not null default 'pending', order_status public.order_status not null default 'pending', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id) on delete set null, product_name text not null, sku text, unit_price numeric(12,2) not null, quantity integer not null check(quantity > 0), created_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.product_images enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security;
create policy "public catalog reads" on public.categories for select using (true); create policy "public product reads" on public.products for select using (is_active = true); create policy "public product image reads" on public.product_images for select using (true);
create policy "customers view own profile" on public.profiles for select using (auth.uid() = id); create policy "customers update own profile" on public.profiles for update using (auth.uid() = id);
create policy "customers view own orders" on public.orders for select using (auth.uid() = customer_id); create policy "customers view own order items" on public.order_items for select using (exists(select 1 from public.orders o where o.id=order_id and o.customer_id=auth.uid()));
-- Order creation and all admin mutations should be performed by validated server-side code using the service role; never expose that key to the browser.
create index products_category_idx on public.products(category_id); create index products_active_idx on public.products(is_active); create index orders_customer_idx on public.orders(customer_id);
